In [1]:
# Homework 1
# Olivia Johnson

In [22]:
# Question 1
DNA='GTTGATGTAGCTTATATAAAGCAAGGCACTGAAAATGCCTAGATGAGTCATAGACTCCATAAACAACAGGTTTGGTCCCGGCCTTTTTATTAGCTGTCTGCAGGATTATACATGCAAAAATCCCTACACCGGTGAGAATGCCCTATGTACCACACTCAGGTTTAAAGGAGCAGACATCAAGCACACTGCTAAGTAGCTCACGACGTCTTGCTT'
print("DNA: ", DNA)
print("Q1.1: DNA length: ", len(DNA))
print("Q1.2: First letter of DNA: ", DNA[0])
print("Q1.3: Last letter of DNA: ", DNA[-1])
print("Q1.4: First 10 characters of DNA: ", DNA[:10])
print("Q1.5: Last 10 characters of DNA: ", DNA[-10:])
print("Q1.6: Count of 'C' in DNA: ", DNA.count('C'))
if DNA.find('CCAAT')!=-1:
  print("Q1.7: Index of CCAAT", DNA.find('CCAAT'))
else:
  print("Q1.7: The motif is not found")

DNA:  GTTGATGTAGCTTATATAAAGCAAGGCACTGAAAATGCCTAGATGAGTCATAGACTCCATAAACAACAGGTTTGGTCCCGGCCTTTTTATTAGCTGTCTGCAGGATTATACATGCAAAAATCCCTACACCGGTGAGAATGCCCTATGTACCACACTCAGGTTTAAAGGAGCAGACATCAAGCACACTGCTAAGTAGCTCACGACGTCTTGCTT
Q1.1: DNA length:  213
Q1.2: First letter of DNA:  G
Q1.3: Last letter of DNA:  T
Q1.4: First 10 characters of DNA:  GTTGATGTAG
Q1.5: Last 10 characters of DNA:  CGTCTTGCTT
Q1.6: Count of 'C' in DNA:  49
Q1.7: The motif is not found

In [23]:
# Question 2
if DNA[:10]== DNA[-10:]:
  print("Q2.1: First 10 and last 10 characters are equal: TRUE")
else:
  print("Q2.1: First 10 and last 10 characters NOT equal")

if DNA.count('C')==DNA.count('A'):
  print("Q2.2: Number of Cs and As are equal")
else:
  print("Q2.2: Number of Cs and As are NOT equal")

Q2.1: First 10 and last 10 characters NOT equal
Q2.2: Number of Cs and As are NOT equal

In [24]:
# Question 3
print("Q3.1 Number of 'C' greater than or equal to Number of 'A':", DNA.count('C')>=DNA.count('A'))
print("Q3.2 Index of first 'C' greater than index of first 'A':", DNA.find('C')>DNA.find('A'))

Q3.1 Number of 'C' greater than or equal to Number of 'A': False
Q3.2 Index of first 'C' greater than index of first 'A': True

In [26]:
# Question 4
print("Q4.1", DNA.count('C')>DNA.count('A') and DNA.count('C')<DNA.count('G'))
print("Q4.2",  DNA.count('C')>DNA.count('A') or DNA.count('C')<DNA.count('G'))
x=8
y=9
print("Q4.3", not(not(x<3) and not(y>14 or y>10)))

Q4.1 False
Q4.2 False
Q4.3 False

In [27]:
# Question 5
print("Q5.1: Output will be 'Medium'")
area = 10.0
if(area < 9) :
    print("small")
elif(area < 12) :
    print("medium")
else :
    print("large")

print('Q5.2:')
if len(DNA)<100:
  print("The DNA sequence is short")
elif len(DNA)<500:
  print("The DNA sequence is medium")
else:
  print("The length is long")

Q5.1: Output will be 'Medium'
medium
Q5.2:
The DNA sequence is medium

In [28]:
# Question 6
print("Q6.1 the while loop will printout 3 values:")
x = 1
while x < 4 :
    print(x)
    x = x + 1

print("Q6.2:")
n=0
while DNA[n]!='C':
  print(DNA[n])
  n=n+1

print("Q6.3:")
i=0
while i< len(DNA):
  if DNA[i]=='C':
    i=i+1
  else:
    print(DNA[i])
    i=i+1

print("Q6.4:")
i=0
while i< len(DNA):
  if DNA[i]=='C' or DNA[i]=='G':
    i=i+1
  else:
    print(DNA[i])
    i=i+1


print("Q6.5:")
i=0
while i< len(DNA):
  if DNA[i]=='A' or DNA[i]=='G':
    print(DNA[i])
    i=i+1
  else:
    i=i+1

Q6.1 the while loop will printout 3 values:
1
2
3
Q6.2:
G
T
T
G
A
T
G
T
A
G
Q6.3:
G
T
T
G
A
T
G
T
A
G
T
T
A
T
A
T
A
A
A
G
A
A
G
G
A
T
G
A
A
A
A
T
G
T
A
G
A
T
G
A
G
T
A
T
A
G
A
T
A
T
A
A
A
A
A
A
G
G
T
T
T
G
G
T
G
G
T
T
T
T
T
A
T
T
A
G
T
G
T
T
G
A
G
G
A
T
T
A
T
A
A
T
G
A
A
A
A
A
T
T
A
A
G
G
T
G
A
G
A
A
T
G
T
A
T
G
T
A
A
A
T
A
G
G
T
T
T
A
A
A
G
G
A
G
A
G
A
A
T
A
A
G
A
A
T
G
T
A
A
G
T
A
G
T
A
G
A
G
T
T
T
G
T
T
Q6.4:
T
T
A
T
T
A
T
T
A
T
A
T
A
A
A
A
A
A
T
A
A
A
A
T
T
A
A
T
A
T
A
T
A
A
T
A
T
A
A
A
A
A
A
T
T
T
T
T
T
T
T
T
A
T
T
A
T
T
T
A
A
T
T
A
T
A
A
T
A
A
A
A
A
T
T
A
A
T
A
A
A
T
T
A
T
T
A
A
A
T
A
T
T
T
A
A
A
A
A
A
A
T
A
A
A
A
T
T
A
A
T
A
T
A
A
T
T
T
T
T
Q6.5:
G
G
A
G
A
G
A
A
A
A
A
G
A
A
G
G
A
G
A
A
A
A
G
A
G
A
G
A
G
A
A
G
A
A
A
A
A
A
A
A
G
G
G
G
G
G
A
A
G
G
G
A
G
G
A
A
A
A
G
A
A
A
A
A
A
A
G
G
G
A
G
A
A
G
A
G
A
A
A
A
G
G
A
A
A
G
G
A
G
A
G
A
A
A
A
G
A
A
G
A
A
G
A
G
A
G
A
G
G

In [29]:
# Question 7
course_ids=['CSCI1020', 'CSCI1030', 'CSCI1070']
for id in course_ids: 
  print("Q7.1: The course id is", id)

print("Q7.2:")
for x in DNA:
  if x =='C':
    break
  else:
    print(x)

print("Q7.3:")
for x in DNA:
  if x=='G' or x=='A':
    print(x)

Q7.1: The course id is CSCI1020
Q7.1: The course id is CSCI1030
Q7.1: The course id is CSCI1070
Q7.2:
G
T
T
G
A
T
G
T
A
G
Q7.3:
G
G
A
G
A
G
A
A
A
A
A
G
A
A
G
G
A
G
A
A
A
A
G
A
G
A
G
A
G
A
A
G
A
A
A
A
A
A
A
A
G
G
G
G
G
G
A
A
G
G
G
A
G
G
A
A
A
A
G
A
A
A
A
A
A
A
G
G
G
A
G
A
A
G
A
G
A
A
A
A
G
G
A
A
A
G
G
A
G
A
G
A
A
A
A
G
A
A
G
A
A
G
A
G
A
G
A
G
G

In [30]:
# Question 8
CS_courses= {"CSCI1020": "Intro to bioinformatics",
             "CSCI1030": "Intro to Game Design",
             "CSCI1070":"Intro to Big Data"}
for key, value in CS_courses.items():
  print("Q8: The course name of", key,"is", value)

Q8: The course name of CSCI1020 is Intro to bioinformatics
Q8: The course name of CSCI1030 is Intro to Game Design
Q8: The course name of CSCI1070 is Intro to Big Data

In [31]:
# Question 9
i= 0
count=0
for i in range(0, len(DNA)-1):
  if DNA[i]== DNA[i+1]:
    count= count+1
    i=i+1
  else:
    i=i+1
print("Q9.1:", count)

a= 0
count_2=0
for a in range(0, len(DNA)-2):
  if DNA[a]== DNA[a+1] and DNA[a+1]==DNA[a+2]:
    count_2= count_2+1
    a=a+1
  else:
    a=a+1
print("Q9.2:", count_2)

b=0
count_3=0
for b in range(0,len(DNA)-1):
  if DNA[b:b+5]=="CCCAT" or DNA[b:b+5]=="CCGAT" or DNA[b:b+5]=="CCTAT" or DNA[b:b+5]=="CCAAT":
    count_3=count_3+1
    z=b
    b=b+1
  else:
    b=b+1
print("Q9.3:", count_3)

print("Q9.4: The motif CC?AT occurs at:", z)
per= DNA.count("CCAAT")
print("Q9.4: The middle nucleotide is an A occurs",per/count_3*100, "percent of the time")

Q9.1: 51
Q9.2: 16
Q9.3: 1
Q9.4: The motif CC?AT occurs at: 141
Q9.4: The middle nucleotide is an A occurs 0.0 percent of the time

In [32]:
# Question 10
dna2dna = {'A':'T', 'T':'A', 'C':'G', 'G':'C'}
def reverse_complement(dna):
    """Return a string representing the reverse complement of the single dna strand."""
    other = ''              # start with an empty string
    for base in dna:
        other = other + dna2dna[base]
    return other[ : :-1]

def mutate(dna, motif):
  x= dna.find(motif)
  spliced=[]
  if dna.find(motif)>=0:
    length= len(motif)
    y= dna.find(reverse_complement(motif),x)
    spliced= dna[0:x]+dna[y+length:]
    return(spliced)
  else:
    return(dna)

print(reverse_complement("G"))
mutate('AGTCACATGATCAGT',"C")

C

'AGTATCAGT'

In [33]:
test_data = """ATCCGAATACGGTTCGGGTA CGAA
ATCCGAATACGGTTGGGTA CGAA
ATCCAATACGGTTCGGGTA CGAA
ATCCGAATACGGTTCGGGTTCGA	CGAA
AGTCACATGATCAGT	C"""
for dna,motif in [line.split() for line in test_data.split('\n')[0:]]:
    print('Executing mutate(%s,%s)...' % (dna,motif))
    print('  returned: %s' % (mutate(dna,motif)))

Executing mutate(ATCCGAATACGGTTCGGGTA,CGAA)...
  returned: ATCGGTA
Executing mutate(ATCCGAATACGGTTGGGTA,CGAA)...
  returned: ATCCGAATACGGTTGGGTA
Executing mutate(ATCCAATACGGTTCGGGTA,CGAA)...
  returned: ATCCAATACGGTTCGGGTA
Executing mutate(ATCCGAATACGGTTCGGGTTCGA,CGAA)...
  returned: ATCGGTTCGA
Executing mutate(AGTCACATGATCAGT,C)...
  returned: AGTATCAGT

In [34]:
my_test= """ATCATGCTAGTCGGATGCCCTAATTA CCCTA
    ACCTATCCGACTAGCTAGCTGGA ATCC
    ACTGAGTC C
    ACTTCAGGGTAGCTAGCTGAG TTA
    ATCTTATCTAGTCGGACTGGCCATC GG
    AAAAAAAAATTTTTTTTCCCCCGGGAA AAA
    ATGCTAGCTGATGGCTAAATCCGATTAA GCT
    ACGATCATATCAT GAT
    AAGTTAGCGATCTGGCAGTAACTTAG AGTTA
    CGTATGCGATTGCATAGC TATGC"""
for dna,motif in [line.split() for line in my_test.split('\n')[0:]]:
    print('Executing mutate(%s,%s)...' % (dna,motif))
    print('  returned: %s' % (mutate(dna,motif)))

Executing mutate(ATCATGCTAGTCGGATGCCCTAATTA,CCCTA)...
  returned: ATCATGCTAGTCGGATGTGCTAGTCGGATGCCCTAATTA
Executing mutate(ACCTATCCGACTAGCTAGCTGGA,ATCC)...
  returned: ACCTTATCCGACTAGCTAGCTGGA
Executing mutate(ACTGAGTC,C)...
  returned: AAGTC
Executing mutate(ACTTCAGGGTAGCTAGCTGAG,TTA)...
  returned: ACTTCAGGGTAGCTAGCTGAG
Executing mutate(ATCTTATCTAGTCGGACTGGCCATC,GG)...
  returned: ATCTTATCTAGTCATC
Executing mutate(AAAAAAAAATTTTTTTTCCCCCGGGAA,AAA)...
  returned: TTTTTCCCCCGGGAA
Executing mutate(ATGCTAGCTGATGGCTAAATCCGATTAA,GCT)...
  returned: ATTGATGGCTAAATCCGATTAA
Executing mutate(ACGATCATATCAT,GAT)...
  returned: ACATATCAT
Executing mutate(AAGTTAGCGATCTGGCAGTAACTTAG,AGTTA)...
  returned: ATAG
Executing mutate(CGTATGCGATTGCATAGC,TATGC)...
  returned: CGGC